# Generated by Django 5.0.6 on 2024-06-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_products_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Products_info',
        ),
    ]
