# Generated by Django 5.0.6 on 2024-06-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_products_products_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_info',
            name='count',
        ),
    ]
