# Generated by Django 5.0.6 on 2024-06-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_products_info_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_info',
            new_name='Products',
        ),
    ]
