# Generated by Django 5.0.6 on 2024-06-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
