# Generated by Django 5.0.6 on 2024-06-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_products_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_discount',
            new_name='product_discount',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_gst',
            new_name='product_gst',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='p_quantity',
            new_name='product_quantity',
        ),
    ]
