# Generated by Django 5.0.6 on 2024-06-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gst',
            new_name='GST',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='f_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='l_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_number',
            new_name='phonenumber',
        ),
    ]
