# Generated by Django 5.0.6 on 2024-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_profile_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
