# Generated by Django 5.0.6 on 2024-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_profiles_adress_alter_profiles_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerAddress', models.CharField(max_length=200)),
                ('CustomerMobileNumber', models.BigIntegerField()),
                ('CustomerGST', models.CharField(max_length=15)),
            ],
        ),
    ]
