# Generated by Django 5.0.6 on 2024-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='gstResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('OrginalAmount', models.IntegerField()),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
