# Generated by Django 5.0.6 on 2024-06-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_gstresult_customername_gstresult_customerphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstresult',
            name='storeName',
        ),
        migrations.RemoveField(
            model_name='gstresult',
            name='storeNumber',
        ),
    ]
