# Generated by Django 5.0.6 on 2024-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_gstresult_storename_gstresult_storenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstresult',
            old_name='storeNumber',
            new_name='storePhone',
        ),
    ]
