# Generated by Django 5.0.6 on 2024-06-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_storenumber_gstresult_storephone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gstresult',
            table='gstResult',
        ),
    ]
